cd ..\..\tools\imagens
c:\lazarus\tools\lazres ACBr_LCL.lrs  TACBrECF.bmp TACBrCalculadora.bmp TACBrGAV.bmp TACBrCHQ.bmp TACBrLCB.bmp TACBrDIS.bmp TACBrExtenso.bmp TACBrValidador.bmp TACBrBAL.bmp TACBrTER.bmp TACBrTroco.bmp TACBrCMC7.bmp TACBrFala.bmp TACBrETQ.bmp TACBrSintegra.bmp TACBrTEF.bmp TACBrRFD.bmp TACBrGIF.bmp TACBrBarCode.bmp TACBrTCPServer.bmp
cd ..\..\source\Pascal
move ..\..\tools\imagens\ACBr_LCL.lrs .\
