VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ModeloECF"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Public Enum ACBrModeloECF
    
    Nenhum = 0
    NaoFiscal = 1
    Bematech = 2
    Sweda = 3
    Daruma = 4
    Schalter = 5
    Mecaf = 6
    Yanco = 7
    DataRegis = 8
    Urano = 9
    ICash = 10
    Quattro = 11
    FiscNET = 12
    Epson = 13
    NCR = 14
    SwedaSTX = 15
        
End Enum
