CLEAR

*Modelos de ECF
#DEFINE ECF_Nenhum 0
#DEFINE ECF_NaoFiscal 1
#DEFINE ECF_Bematech 2
#DEFINE ECF_Sweda 3
#DEFINE ECF_Daruma 4
#DEFINE ECF_Schalter 5
#DEFINE ECF_Mecaf 6
#DEFINE ECF_Yanco 7
#DEFINE ECF_DataRegis 8
#DEFINE ECF_Urano 9
#DEFINE ECF_ICash 10
#DEFINE ECF_Quattro 11
#DEFINE ECF_FiscNET 12
#DEFINE ECF_Epson 13
#DEFINE ECF_NCR 14
#DEFINE ECF_SwedaSTX 15

* ESTADOS DO ECF
#DEFINE ESTADO_NaoInicializada 0
#DEFINE ESTADO_Desconhecido 1
#DEFINE ESTADO_Livre 2
#DEFINE ESTADO_Venda 3
#DEFINE ESTADO_Pagamento 4
#DEFINE ESTADO_Relatorio 5
#DEFINE ESTADO_Bloqueada 6
#DEFINE ESTADO_RequerZ 7
#DEFINE ESTADO_RequerX 8
#DEFINE ESTADO_NaoFiscal 9

PUBLIC iHandle

* Carrega as declarações das funções da DLL
DO acbr32dll_dec.prg

DEACTIVATE WINDOW SCREEN
DO FORM acbr32frm

ON SHUTDOWN QUIT

READ EVENTS

CLEAR WINDOW ALL
CLEAR DLLS
CLEAR ALL
